lobbyConfig:
  maxCount: 2
  showLicense: true

clientServer:
  hostname: "*"
  port: 2106

bridgeServer:
  hostname: "127.0.0.1"
  port: 2100

registeredServers:
  - id: 0
    ip: "172.20.10.8"
    port: 7777
    ageLimit: 18
    isPvp: false
    onlineCount: 0
    maxOnline: 5
    blowFishKey: "fhgj#G$FSWD&T&#3"
  - id: 1
    ip: "172.20.10.8"
    port: 7777
    ageLimit: 18
    isPvp: false
    onlineCount: 0
    maxOnline: 5
    blowFishKey: "ghJW&^#TEyuGOE*G"