lobbyConfig:
  maxCount: 2
  showLicense: true

clientServer:
  hostname: "*"
  port: 2106

bridgeServer:
  hostname: "127.0.0.1"
  port: 2100

registeredServers:
  - id: 1
    ip: "172.20.10.8"
    port: 7777
    ageLimit: 18
    isPvp: false
    maxOnline: 5
    bridgeKey: "fhgj#G$FSWD&T&#3"
  - id: 2
    ip: "192.168.43.144"
    port: 7777
    ageLimit: 18
    isPvp: false
    maxOnline: 5
    bridgeKey: "ghJW&^#TEyuGOE*G"